services:
  pocketbase:
    build:
      context: ./pocketbase
      args:
        PB_VERSION: 0.39.1
    ports:
      - "8090:8080"
    volumes:
      - ./pocketbase/pb_data:/pb/pb_data
    restart: unless-stopped
